# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\x1a\x1cgoogle/protobuf/struct.proto\"5\n\x07\x44\x42Query\x12\x0b\n\x03sql\x18\x01 \x01(\t\x12\x0e\n\x06params\x18\x02 \x03(\t\x12\r\n\x05token\x18\x03 \x01(\t\"\xe7\x01\n\x10InferenceRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\r\n\x03raw\x18\x02 \x01(\x0cH\x00\x12.\n\x0bstruct_data\x18\x04 \x01(\x0b\x32\x17.google.protobuf.StructH\x00\x12\r\n\x05level\x18\x03 \x01(\t\x12\x0e\n\x06stream\x18\x05 \x01(\x08\x12\x12\n\nsession_id\x18\n \x01(\t\x12\x10\n\x08\x63hunk_id\x18\x0b \x01(\x05\x12\x12\n\nlast_chunk\x18\x0c \x01(\x08\x12$\n\x08\x64\x62_query\x18\x14 \x01(\x0b\x32\x12.inference.DBQueryB\x06\n\x04\x64\x61ta\"|\n\x11InferenceResponse\x12\r\n\x03raw\x18\x01 \x01(\x0cH\x00\x12.\n\x0bstruct_data\x18\x04 \x01(\x0b\x32\x17.google.protobuf.StructH\x00\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x11\n\tmeta_json\x18\x03 \x01(\tB\x06\n\x04\x64\x61ta2S\n\tInference\x12\x46\n\x05Infer\x12\x1b.inference.InferenceRequest\x1a\x1c.inference.InferenceResponse(\x01\x30\x01\x42\rZ\x0binferencepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013inferencepb'
  _globals['_DBQUERY']._serialized_start=60
  _globals['_DBQUERY']._serialized_end=113
  _globals['_INFERENCEREQUEST']._serialized_start=116
  _globals['_INFERENCEREQUEST']._serialized_end=347
  _globals['_INFERENCERESPONSE']._serialized_start=349
  _globals['_INFERENCERESPONSE']._serialized_end=473
  _globals['_INFERENCE']._serialized_start=475
  _globals['_INFERENCE']._serialized_end=558
# @@protoc_insertion_point(module_scope)
