# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trainer.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'trainer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtrainer.proto\x12\x07trainer\x1a\x1bgoogle/protobuf/empty.proto\"\x91\x02\n\x0cTrainRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x11\n\tknowledge\x18\x06 \x03(\t\x12;\n\x0bhyperparams\x18\x03 \x03(\x0b\x32&.trainer.TrainRequest.HyperparamsEntry\x12\x0e\n\x06gpu_id\x18\x04 \x01(\r\x12\x0e\n\x06job_id\x18\x05 \x01(\t\x12\x0c\n\x04name\x18\x07 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x08 \x01(\t\x12\x13\n\x0binstruction\x18\t \x01(\t\x1a\x32\n\x10HyperparamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01J\x04\x08\x02\x10\x03R\x0b\x64\x61taset_uri\"\xf7\x01\n\rTrainProgress\x12\x0c\n\x04step\x18\x01 \x01(\r\x12\x13\n\x0btotal_steps\x18\x02 \x01(\r\x12\x0c\n\x04loss\x18\x03 \x01(\x01\x12\x0e\n\x06metric\x18\x04 \x01(\x01\x12+\n\x05stage\x18\x05 \x01(\x0e\x32\x1c.trainer.TrainProgress.Stage\x12\x0e\n\x06job_id\x18\x06 \x01(\t\x12\x0f\n\x07message\x18\x07 \x01(\t\"W\n\x05Stage\x12\x0c\n\x08RECEIVED\x10\x00\x12\r\n\tPREPARING\x10\x01\x12\t\n\x05READY\x10\x02\x12\x0c\n\x08TRAINING\x10\x03\x12\x0c\n\x08\x43OMPLETE\x10\x04\x12\n\n\x06\x46\x41ILED\x10\x05\"D\n\nTrainReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0c\x61rtifact_uri\x18\x03 \x01(\t2\x82\x01\n\x07Trainer\x12;\n\x08StartJob\x12\x15.trainer.TrainRequest\x1a\x16.trainer.TrainProgress0\x01\x12:\n\tCancelJob\x12\x15.trainer.TrainRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trainer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAINREQUEST_HYPERPARAMSENTRY']._loaded_options = None
  _globals['_TRAINREQUEST_HYPERPARAMSENTRY']._serialized_options = b'8\001'
  _globals['_TRAINREQUEST']._serialized_start=56
  _globals['_TRAINREQUEST']._serialized_end=329
  _globals['_TRAINREQUEST_HYPERPARAMSENTRY']._serialized_start=260
  _globals['_TRAINREQUEST_HYPERPARAMSENTRY']._serialized_end=310
  _globals['_TRAINPROGRESS']._serialized_start=332
  _globals['_TRAINPROGRESS']._serialized_end=579
  _globals['_TRAINPROGRESS_STAGE']._serialized_start=492
  _globals['_TRAINPROGRESS_STAGE']._serialized_end=579
  _globals['_TRAINREPLY']._serialized_start=581
  _globals['_TRAINREPLY']._serialized_end=649
  _globals['_TRAINER']._serialized_start=652
  _globals['_TRAINER']._serialized_end=782
# @@protoc_insertion_point(module_scope)
